
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.hostname = "debian-bookworm"
  config.vm.provision "shell", inline: <<-SHELL
   apt-get update
   apt upgrade -y
   apt-get install -y nginx
   SHELL
 end
 